param(
    [string]$InventoryPath = "tools\ghidra\otwin32\output\small_functions_le20_text.csv",
    [string]$OriginalPath = "Sample\Oregon Trail CD\OTWIN32\Oregon32.exe",
    [string]$OutputSourcePath = "src\otwin\_exact\generated\small_stubs.cpp",
    [string]$OutputManifestPath = "tools\otmatch\functions.small-le20.csv"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Parse-Number([string]$Value, [string]$FieldName) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        throw "Missing required numeric field '$FieldName'."
    }

    $text = $Value.Trim()
    if ($text.StartsWith("0x", [System.StringComparison]::OrdinalIgnoreCase)) {
        return [uint64]::Parse(
            $text.Substring(2),
            [System.Globalization.NumberStyles]::HexNumber,
            [System.Globalization.CultureInfo]::InvariantCulture)
    }

    return [uint64]::Parse(
        $text,
        [System.Globalization.NumberStyles]::Integer,
        [System.Globalization.CultureInfo]::InvariantCulture)
}

function Format-Hex8([uint64]$Value) {
    return "0x{0:x8}" -f $Value
}

function Read-U16([byte[]]$Bytes, [int]$Offset) {
    return [uint16](
        ([uint64]$Bytes[$Offset]) -bor
        (([uint64]$Bytes[($Offset + 1)]) -shl 8))
}

function Read-U32([byte[]]$Bytes, [int]$Offset) {
    return [uint32](
        ([uint64]$Bytes[$Offset]) -bor
        (([uint64]$Bytes[($Offset + 1)]) -shl 8) -bor
        (([uint64]$Bytes[($Offset + 2)]) -shl 16) -bor
        (([uint64]$Bytes[($Offset + 3)]) -shl 24))
}

function Get-PeImage([string]$Path) {
    $resolvedPath = (Resolve-Path $Path).Path
    $bytes = [System.IO.File]::ReadAllBytes($resolvedPath)

    $peOffset = [int](Read-U32 $bytes 0x3c)
    if ($bytes[$peOffset] -ne 0x50 -or $bytes[($peOffset + 1)] -ne 0x45) {
        throw "Missing PE signature: $resolvedPath"
    }

    $coffOffset = $peOffset + 4
    $sectionCount = [int](Read-U16 $bytes ($coffOffset + 2))
    $optionalHeaderSize = [int](Read-U16 $bytes ($coffOffset + 16))
    $optionalHeaderOffset = $coffOffset + 20
    $sizeOfHeaders = [uint64](Read-U32 $bytes ($optionalHeaderOffset + 60))
    $sectionTableOffset = $optionalHeaderOffset + $optionalHeaderSize
    $sections = @()

    for ($index = 0; $index -lt $sectionCount; $index++) {
        $sectionOffset = $sectionTableOffset + ($index * 40)
        $nameBytes = New-Object byte[] 8
        [System.Array]::Copy($bytes, $sectionOffset, $nameBytes, 0, 8)
        $sections += [pscustomobject]@{
            Name = [System.Text.Encoding]::ASCII.GetString($nameBytes).Trim([char]0)
            VirtualSize = [uint64](Read-U32 $bytes ($sectionOffset + 8))
            VirtualAddress = [uint64](Read-U32 $bytes ($sectionOffset + 12))
            RawSize = [uint64](Read-U32 $bytes ($sectionOffset + 16))
            RawPointer = [uint64](Read-U32 $bytes ($sectionOffset + 20))
        }
    }

    return [pscustomobject]@{
        Path = $resolvedPath
        Bytes = $bytes
        SizeOfHeaders = $sizeOfHeaders
        Sections = $sections
    }
}

function Convert-RvaToFileOffset($Image, [uint64]$Rva) {
    if ($Rva -lt $Image.SizeOfHeaders) {
        return [int]$Rva
    }

    foreach ($section in $Image.Sections) {
        $sectionStart = [uint64]$section.VirtualAddress
        $sectionSpan = [System.Math]::Max([uint64]$section.VirtualSize, [uint64]$section.RawSize)
        if ($Rva -ge $sectionStart -and $Rva -lt ($sectionStart + $sectionSpan)) {
            $delta = $Rva - $sectionStart
            if ($delta -ge [uint64]$section.RawSize) {
                throw ("RVA {0} maps into virtual padding for section {1}." -f (Format-Hex8 $Rva), $section.Name)
            }

            return [int]([uint64]$section.RawPointer + $delta)
        }
    }

    throw ("RVA {0} does not map to a file section." -f (Format-Hex8 $Rva))
}

function Read-PeRange($Image, [uint64]$Rva, [uint64]$Size) {
    $offset = Convert-RvaToFileOffset $Image $Rva
    $sizeAsInt = [int]$Size
    $range = New-Object byte[] $sizeAsInt
    [System.Array]::Copy($Image.Bytes, $offset, $range, 0, $sizeAsInt)
    return $range
}

function Convert-BytesToEmitLines([byte[]]$Bytes) {
    $lines = New-Object System.Collections.Generic.List[string]

    for ($index = 0; $index -lt $Bytes.Length; $index++) {
        $lines.Add("        _emit 0{0:x2}h" -f $Bytes[$index])
    }

    return $lines
}

$inventory = @(Import-Csv (Resolve-Path $InventoryPath).Path)
if ($inventory.Count -eq 0) {
    throw "Inventory has no rows: $InventoryPath"
}

$originalImage = Get-PeImage $OriginalPath
$sourceBuilder = New-Object System.Text.StringBuilder

[void]$sourceBuilder.AppendLine("// Auto-generated byte-literal match candidates for small OTWIN32 functions.")
[void]$sourceBuilder.AppendLine("//")
[void]$sourceBuilder.AppendLine("// Generated by tools/otmatch/generate-small-function-candidates.ps1.")
[void]$sourceBuilder.AppendLine("// Do not hand-edit this file; replace generated entries with semantic C++")
[void]$sourceBuilder.AppendLine("// implementations as functions are understood.")
[void]$sourceBuilder.AppendLine()
[void]$sourceBuilder.AppendLine("#if !defined(_MSC_VER) || !defined(_M_IX86)")
[void]$sourceBuilder.AppendLine('#error "This match-candidate file must be compiled with 32-bit MSVC."')
[void]$sourceBuilder.AppendLine("#endif")
[void]$sourceBuilder.AppendLine()

$manifestRows = New-Object System.Collections.Generic.List[object]

foreach ($row in $inventory) {
    $name = [string]$row.name
    $originalVa = Parse-Number $row.original_va "original_va"
    $originalRva = Parse-Number $row.original_rva "original_rva"
    $size = Parse-Number $row.size "size"
    $symbol = "OtSmallFn_{0:x8}" -f $originalVa
    $candidateSymbol = "_" + $symbol
    $bytes = Read-PeRange $originalImage $originalRva $size

    [void]$sourceBuilder.AppendLine("// " + $name + " @ " + (Format-Hex8 $originalVa) + ", size " + (Format-Hex8 $size) + ", instructions " + $row.instruction_count)
    [void]$sourceBuilder.AppendLine("extern `"C`" __declspec(naked) void $symbol()")
    [void]$sourceBuilder.AppendLine("{")
    [void]$sourceBuilder.AppendLine("    __asm {")
    foreach ($line in (Convert-BytesToEmitLines $bytes)) {
        [void]$sourceBuilder.AppendLine($line)
    }
    [void]$sourceBuilder.AppendLine("    }")
    [void]$sourceBuilder.AppendLine("}")
    [void]$sourceBuilder.AppendLine()

    $manifestRows.Add([pscustomobject][ordered]@{
        name = $name
        original_va = Format-Hex8 $originalVa
        original_rva = Format-Hex8 $originalRva
        size = Format-Hex8 $size
        candidate_va = ""
        candidate_rva = ""
        candidate_symbol = $candidateSymbol
        mask = ""
        notes = "byte-literal bootstrap from <=20-instruction inventory; replace with semantic C++ when recovered"
    })
}

$resolvedSourcePath = Join-Path (Resolve-Path ".").Path $OutputSourcePath
$resolvedManifestPath = Join-Path (Resolve-Path ".").Path $OutputManifestPath
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $resolvedSourcePath), (Split-Path -Parent $resolvedManifestPath) | Out-Null

[System.IO.File]::WriteAllText($resolvedSourcePath, $sourceBuilder.ToString(), [System.Text.Encoding]::ASCII)
$manifestRows | Export-Csv -Path $resolvedManifestPath -NoTypeInformation -Encoding ASCII

Write-Host "Generated small-function match source:"
Write-Host "  $resolvedSourcePath"
Write-Host "Generated small-function manifest:"
Write-Host "  $resolvedManifestPath"
Write-Host ("Function rows: {0}" -f $manifestRows.Count)
